// Isolated real server/SQLite; never reads or changes the exhibition database.
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createSurveyServer, createContext } from '../survey/src/server/server.ts';
const { chromium } = await import('../qr-hud/node_modules/@playwright/test/index.mjs');
const directory=await mkdtemp(join(tmpdir(),'city-mobile-lite-'));
const evidence=process.env.CITY2127_EVIDENCE_DIR || 'artifacts/mobile-lite';
await mkdir(evidence,{recursive:true});
const ctx=createContext({dbPath:join(directory,'survey.sqlite'),questionsPath:fileURLToPath(new URL('../survey/src/survey/questions.exhibition.json',import.meta.url))});
const {server,realtime}=createSurveyServer({ctx,staticDir:fileURLToPath(new URL('../survey/dist',import.meta.url)),cityDir:fileURLToPath(new URL('../dist-exhibition',import.meta.url))});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const base=`http://127.0.0.1:${server.address().port}`;
const api=async(path,body)=>{const response=await fetch(base+path,body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{});assert.ok(response.ok,`${path}: ${response.status}`);return (await response.json()).data;};
const browser=await chromium.launch({channel:'chrome',headless:true});
const errors=[],report={scratchDirectory:directory,browser:browser.version(),platform:process.platform,cases:[]};
let sockets=0;
async function open(url,options){
  const context=await browser.newContext(options),page=await context.newPage(),requests=[];
  page.setDefaultTimeout(120000);
  page.on('pageerror',error=>errors.push(error.message));
  page.on('console',message=>{if(/THREE.WebGLProgram: Shader Error/.test(message.text()))errors.push(message.text());});
  page.on('websocket',()=>sockets++);
  page.on('request',request=>requests.push(request.url()));
  await page.goto(url,{waitUntil:'domcontentloaded'});
  await page.locator('canvas[data-archive-id][data-scene-ready=true]').waitFor();
  await page.locator('.personal-loading').waitFor({state:'detached'});
  return {context,page,requests};
}
try{
  const session=await api('/api/proposal-sessions',{});
  const saved=await api('/api/proposals',{submissionId:crypto.randomUUID(),guestSessionId:session.session.id,expectedRevision:session.state.revision,answers:session.questions.map(q=>({questionId:q.id,optionId:q.options.at(-1).id}))});
  const id=saved.proposal.id,url=`${base}/city/${id}?survey`;
  const archived=await (await fetch(`${base}/api/archives/${id}`)).json();
  const phoneOptions={viewport:{width:390,height:844},deviceScaleFactor:3,isMobile:true,hasTouch:true,userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1'};
  const {context,page,requests}=await open(url,phoneOptions);
  const canvas=page.locator('canvas');
  assert.equal(await canvas.getAttribute('data-quality'),'lite');
  assert.equal(await canvas.getAttribute('data-postprocessing'),'false');
  assert.deepEqual(JSON.parse(await canvas.getAttribute('data-layout')),archived.view.layout);
  const dimensions=await canvas.evaluate(c=>({width:c.width,height:c.height,cssWidth:c.getBoundingClientRect().width,cssHeight:c.getBoundingClientRect().height,antialias:c.getContext('webgl2').getContextAttributes().antialias}));
  assert.equal(dimensions.cssWidth,390);assert.equal(dimensions.cssHeight,844);
  assert.ok(dimensions.width<=273 && dimensions.height<=720 && !dimensions.antialias);
  assert.ok(!requests.some(url=>/maritime-sky|coastal-grass|bay-ripple-normal/.test(url)),'no heavyweight PNG requests in lite');
  const initial=await canvas.getAttribute('data-camera');
  await page.getByRole('button',{name:'拡大',exact:true}).click();
  await page.waitForFunction(old=>document.querySelector('canvas').dataset.camera!==old,initial);
  const zoomed=await canvas.getAttribute('data-camera'),cdp=await context.newCDPSession(page);
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:160,y:380}]});
  for(let x=170;x<=250;x+=20)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:400}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await page.waitForFunction(old=>document.querySelector('canvas').dataset.camera!==old,zoomed);
  await page.getByRole('button',{name:'最初の視点',exact:true}).click();
  await page.waitForTimeout(8000);
  await page.screenshot({path:join(evidence,'phone-lite.png')});
  const frames=Number(await canvas.getAttribute('data-render-frames'));
  await page.waitForTimeout(3200);
  const idleFrames=Number(await canvas.getAttribute('data-render-frames'))-frames;
  assert.ok(idleFrames<=5,`idle mode does not continuously render: ${idleFrames}`);
  assert.match(await page.locator('.personal-quality').textContent(),/軽量表示/);
  await page.setViewportSize({width:844,height:390});
  await page.waitForTimeout(700);
  assert.equal(await canvas.evaluate(c=>c.getBoundingClientRect().width),844);
  assert.ok(await canvas.evaluate(c=>c.width<=720 && c.height<=720));
  await page.reload({waitUntil:'domcontentloaded'});
  await page.locator('canvas[data-scene-ready=true]').waitFor();
  assert.deepEqual(JSON.parse(await canvas.getAttribute('data-layout')),archived.view.layout);
  assert.equal(sockets,0,'archive never joins live state even with ?survey');
  await canvas.evaluate(c=>c.dispatchEvent(new Event('webglcontextlost',{cancelable:true})));
  assert.ok((await page.locator('.error a').getAttribute('href')).includes(`/city/${id}?survey=&quality=lite`));
  report.cases.push({name:'iPhone emulated lite',dimensions,idleFrames,archive:id,layout:archived.view.layout});
  await context.close();
  const desktop=await open(`${base}/city/${id}`,{viewport:{width:1280,height:720},deviceScaleFactor:1});
  assert.equal(await desktop.page.locator('canvas').getAttribute('data-quality'),'full');
  assert.equal(await desktop.page.locator('canvas').getAttribute('data-postprocessing'),'true');
  await desktop.page.screenshot({path:join(evidence,'desktop-full.png')});
  report.cases.push({name:'desktop archive full',size:await desktop.page.locator('canvas').evaluate(c=>[c.width,c.height])});
  await desktop.context.close();
  const forced=await open(`${base}/city/${id}?quality=lite`,{viewport:{width:1280,height:720},deviceScaleFactor:1});
  assert.equal(await forced.page.locator('canvas').getAttribute('data-quality'),'lite');
  await forced.context.close();
  const missing=await browser.newPage();
  await missing.goto(`${base}/city/unknown`);await missing.locator('.error').waitFor();
  assert.equal(await missing.locator('canvas').count(),0);await missing.close();
  assert.deepEqual(errors,[]);assert.equal(sockets,0);
  report.errors=errors;report.status='PASS';
  console.log('PASS: automatic phone lite, actual bounded canvas, no large PNGs, touch/zoom/reset, idle gate, resize/reload, archive isolation, context-loss retry, desktop full, explicit lite, unknown archive');
}finally{
  await writeFile(join(evidence,'browser.json'),JSON.stringify(report,null,2));
  await browser.close();realtime.close();await new Promise(resolve=>server.close(resolve));ctx.db.close();
}
