import assert from 'node:assert/strict';
import { createWorldState } from '../src/worldState.ts';
import { presets } from '../src/presets.ts';
const world = createWorldState();
assert.deepEqual(world.state, presets.neutral);
assert.equal(world.choose('pulse', 0), true);
assert.equal(world.choose('still', 5), false);
assert.equal(world.update(5).judgment, false);
assert.ok(Math.abs(world.state.neon - .6) < 1e-10);
assert.equal(world.update(10).judgment, true);
assert.equal(world.update(10).phase, 'hold');
assert.deepEqual(world.state, presets.pulse);
assert.equal(world.choose('still', 13.99), false);
assert.equal(world.choose('still', 14), true);
assert.equal(world.update(24).judgment, true);
for (const key of Object.keys(presets.still) as (keyof typeof presets.still)[]) assert.ok(Math.abs(world.state[key] - presets.still[key]) < 1e-10);
assert.equal(world.choose('neutral', 28), true);
assert.equal(world.update(38).judgment, false);
assert.equal(world.update(42).phase, 'ready');
console.log('PASS: 10s transition, immediate judgment, 4s state lock, repeat selection, neutral reset.');
